### ISSUE TITLE
Write a session plan for the day

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/what-does-health-look-like#13]
So we know what order things are happening in.

**Comment by amcewen** [comment]
Who will look after which parts?
 * Knitting sensors (@Tactile-electronics)
 * Assembling pressure sensors
 * Getting code working (@amcewen)
 * Sublimating (onto mugs or t-shirts)

**Comment by Tactile-electronics** [comment]
Session Plan for Saturday: will add more details

https://github.com/DoESLiverpool/what-does-health-look-like/blob/master/session%20plan
