### ISSUE TITLE
Bag up the kits before the day

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/what-does-health-look-like#14]
Buy ziplock bags (the ones from Home & Bargain with the blue top and the red zip).

Bag up the stuff.

**Comment by Tactile-electronics** [comment]
Done except:
All need stretch sensors, 
Four need USB cables 
one needs a microbit

**Comment by Tactile-electronics** [comment]
Also need 100ohm resistors added to them

**Comment by amcewen** [comment]
This presumably got done :-)
