### ISSUE TITLE
Saturday set up & prep

### ISSUE THREAD

**Issue by Tactile-electronics** [DoESLiverpool/what-does-health-look-like#21]
- [x] Sort out T-shirts into sizes etc

- [x] Set up a laptop with the projector (to show instructions)

- [ ] Set up tables and chairs 

- [x] Laura to get food & refreshments

- [ ] Go through session plan & assign tasks 

- [ ] Make an exampleT-shirt

- [ ] Check tech is working 

- [ ] Add USB cables to the kits without 

- [x] Add stretch sensors to all kits

- [x] Add 100ohm resistors to kits

- [ ] Add microbit to the one kit missing one

- [ ] Set up for sublimation printing 

- [ ] lay out kits

**Comment by amcewen** [comment]
We ran the day, and it was a great success, so we must've done the right prep and setup :-)
