### ISSUE TITLE
Output to Processing sketches to visualise data 

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/what-does-health-look-like#9]
Experiment and write up

Example of heart visualisation shown here: https://rantonse.no/en/blog/2017-03-11

(We'll need a jpg output for t shirts)

**Comment by zarino** [comment]
Written up here: https://github.com/DoESLiverpool/what-does-health-look-like/tree/master/processing

**Comment by amcewen** [comment]
Another half-done experiment at https://www.openprocessing.org/sketch/590088

**Comment by amcewen** [comment]
And a more finished experiment, riffing on Joy Division's Unknown Pleasures album cover https://www.openprocessing.org/sketch/590101

**Comment by Tactile-electronics** [comment]
Jackie to look into fading and accelerometer
